### ISSUE TITLE
Is this role still in use?

### ISSUE THREAD

**Issue by Emmixis** [sighofrelief/CookieDough.py#8]
https://github.com/sighofrelief/CookieDough.py/blob/f5b7f1c742f4d3ccc701901c9205d89941d78d15/cogs/pinboard.py#L26

I don't think ive seen this role at all; is this line dead weight?

**Comment by sapphic-wallflower** [comment]
yeah, that line is pretty useless. it was the old role for being "super vetted". feel free to remove it.
